<section class="col-md-12" id="sort-block" >
    <div class="container">
            <div class="col-md-2 col-sm-12 col-xs-12"><button class="sort btn   btn-lg " id="ascending" value="0">old posts first</button></div>
            <div class="col-md-2  col-sm-12 col-xs-12"><button class="sort btn  btn-lg  " id="descending" value="1">new posts first</button></div>
            <div class="col-md-2   col-sm-12 col-xs-12"><button class="sort btn   btn-lg  " id="descending" value="2">A-Z</button></div>
            <div class="col-md-6   col-sm-12 col-xs-12">
                <form id="author-search-form" class="form-inline" role="search">
                    <div class="form-group">
                        <div class="input-group">
                            <input name="name" id="author-search" class="input-lg form-control"  placeholder="your favourite author"/>
                            <span class="input-group-btn">
                                <button id="author-search-button" class="btn  btn-lg "><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div> 
    </div>
</section>
<section class="col-md-12 col-sm-12 com-lg-12" id="new-posts" data-authors='<?php echo json_encode($this->authors);?>' >
    <div class="container thePosts"> 
    <?php foreach($this->posts as $key=>$post) :?>

            <div class="col-md-5 postContainer" >
                <div class="posts"  data-post="<?php echo $post->getId() ;?>">
                    <a   class="blogSelection" href="blog/show/<?php echo $post->getId();?>">
                    </a>
                </div>
                 <div class='col-md-12 postDetailContainer'>
                    <div class="postCategory"></div>
                    <div class="postTitle"><span class="postHeading"><?php echo $post->getTitle()." ";?></span></div> 
                    <div class="postContent"><?php echo substr($post->getContent(),0,162);?><span> <a  href="blog/show/<?php echo $post->getId();?>"><button style="color:black;"class="btn btn-xs btn-info">read more</button></a></span></div>
                 </div>
            </div>
        <?php  if(intval($key) % 2 == 0 ) : ?>
                <div class="col-md-2">
                </div>  
        <?php endif;?>
        
        
        
    <?php endforeach;?>
    </div>
</section>
<?php echo $this->loginModal;?>
