<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <base href="/house/">
        <meta charset="utf-8">
        <?php echo $this->headTitle('Nepal on board -house') ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('Content-Language', 'en')
            ->appendName('description','Nepalonboard, This is an online booking system targeted at international students to make their journey to new country smooth. ')
            ->appendName('apple-mobile-web-app-capable','yes')
            ->appendName('keywords','booking system, nepalonboard, accommodation, share house, flights, Australia,nepal on board blog')
           
        ?>   
        <!-- Style -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'logo', 'href' => $this->basePath() . '/img/newnobsmall.ico'))
            ->prependStylesheet($this->basePath('javascript/dropzone-4.3.0/dist/min/dropzone.min.css'))
            ->prependStylesheet($this->basePath('bower_components/fullpage.js/dist/jquery.fullpage.css'))
            ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('bower_components/ideal-image-slider/ideal-image-slider.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('bower_components/jquery-ui/themes/base/jquery-ui.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/house/house-style.css'))
            ->prependStylesheet($this->basePath('bower_components/angular-material/angular-material.min.css'))?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('bower_components/jquery-ui/jquery-ui.min.js'))      
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('bower_components/angular-route/angular-route.min.js'))
            ->prependFile($this->basePath('bower_components/angular-aria/angular-aria.min.js'))
            ->prependFile($this->basePath('bower_components/angular-animate/angular-animate.min.js'))
            ->prependFile($this->basePath('bower_components/angular-material/angular-material.min.js'))
            ->prependFile($this->basePath('bower_components/angular/angular.min.js'))
            ->prependFile($this->basePath('javascript/dropzone-4.3.0/dist/min/dropzone.min.js'))
            ->prependFile($this->basePath('bower_components/fullpage.js/dist/jquery.fullpage.min.js'))
            ->prependFile($this->basePath('bower_components/jquery-ui/jquery-ui.min.js'))            
            ->prependFile($this->basePath('javascript/onboard.house.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-79358160-1', 'auto');
            ga('send', 'pageview');
        </script>
           <script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB56xw8q2FvZKEyLWhl7Wxbp1sejoKjb3E&libraries=places"
    async defer></script> 
    </head>
    <body  >
         <div id="loading" ></div>
         <div class="col-md-12 " id="house-top-container" >
            <div id="home-logo" class="col-xs-2 col-md-2 ">
                <img id="our-logo" src="<?php echo $this->basePath() . '/img/newnobsmall.svg'?>"/> 
            </div> 
            <div id="house-login-container" class="col-md-2 ">
            </div>
        </div>
        <div>
         <div id="house-body-container">
             <?php echo $this->content;?>
         </div>
        </div>
    </body>
</html>
