<?php echo $this->doctype(); ?>
<html lang="en" ng-app="houseApp">
    <head>
        <meta charset="utf-8">
        <?php   
            
                $this->headMeta()->setProperty('fb:app_id','596409587196547');
                 if(isset($this->title)){
                $this->headMeta()->setProperty('og:type','article')
                ->setProperty('og:url','http://nepalonboard.com/blog/show/'.$this->id)
                ->setProperty('og:title',$this->title)
                ->setProperty('og:site_name','Nepal On-board')
                ->setProperty('og:image','http://nepalonboard.com/img/posts/post'.$this->id.'.jpg')
                ->setProperty('og:image:type','image/jpg')
                ->setProperty('og:image:width',"400")
                ->setProperty('article:author','https://www.facebook.com/profile.php?id='.$this->fbId)
                ->setProperty('og:image:height',"400")
                ->setProperty('og:description',$this->description);       
            }
        ?>
        <?php echo $this->headTitle('Nepal on board -blog') ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('Content-Language', 'en')
            ->appendName('description','Nepalonboard, This is an online booking system targeted at international students to make their journey to new country smooth. ')
            ->appendName('apple-mobile-web-app-capable','yes')
            ->appendName('keywords','booking system, nepalonboard, accommodation, share house, flights, Australia,nepal on board blog')
          
        ?>
        
        <!-- Style -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'logo', 'href' => $this->basePath() . '/img/newnobsmall.ico'))
            ->prependStylesheet($this->basePath('javascript/dropzone-4.3.0/dist/min/dropzone.min.css'))
            ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('javascript/dropzone-4.3.0/dist/min/dropzone.min.js'))
            ->prependFile($this->basePath('javascript/onboard.blog.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('bower_components/jquery-ui/jquery-ui.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-79358160-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body>
         <div id="loading" ></div>
        <div class="col-md-12 changeMe " id="blog-navbar">
            <div id="home-logo" class="col-xs-2  "><img style="width:75px; height:75px;" src="<?php echo $this->basePath() . '/img/newnobsmall.svg'?>"/> </div>
            <?php if(isset($this->writer)):?>
                <div class="col-md-7 col-xs-6" style="top:1.5em;" id="userNameContainer">
                    <h2 id="user">
                        <?php echo 'Hi '.$this->writer;?>
                    </h2>
                </div>
            <?php endif;?>
            <?php if($this->show):?><div class="col-md-2 col-xs-4" id="blog-menu-nav-container" style="float:right;top:3em"><a href="/blog" id="blog-menu-nav" style="" class="NepalOnBoardLink">Blog Menu</a></div><?php endif;?>
             <?php if(!$this->show):?>
                <div class="col-md-8 col-sm-8 col-xs-7" id="blog-header" >
                   <h1 style="display:none" id="blog-heading"><span class="line">Blog</span></h1>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-3" id="share-your-experience-block">     
                    <h4><a class="shareYourExperience">Write your own blog</a></h4>
                </div>
             <?php endIf ?>
        </div>
        <div class="NepalOnBoardContainer changeMe" id="blog-body" > 
            <?php echo $this->content; ?>
        </div>   
        <?php echo $this->loginModal;?>
         <script>
             function checkLogin(){
                 FB.getLoginStatus(function(response){
                   if(response.status === 'connected'){
                       FB.api('/me/',function(res){
                           window.location.assign('/blog/writer/'+res.name.replace(/\s+/g,'-'));  
                       });
                   }
                 });    
             }
         </script>
    </body>
</html>
