<?php echo $this->doctype(); ?>

<html lang="en" class="no-js">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Nepal On-board') ?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('Content-Language', 'en')
            ->appendName('description','Nepalonboard is an online travel agent and our aim is to give international students a convenient platform to use, taking the pressure off them in planning their journey to a new Country. ')
            ->appendName('apple-mobile-web-app-capable','yes')
            ->appendName('keywords','booking system, nepalonboard, accommodation, share house, flights, Australia')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'logo', 'href' => $this->basePath() . 'img/newnobsmall.ico'))
            ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('bower_components/fullpage.js/dist/jquery.fullpage.css'))
            

        ?>
            
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('bower_components/fullpage.js/vendors/jquery.easings.min.js'))
            ->prependFile($this->basePath('bower_components/fullpage.js/vendors/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('javascript/onboard.initial.js'))
            ->prependFile($this->basePath('bower_components/fullpage.js/dist/jquery.fullpage.min.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))   
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-79358160-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body>   
        <div id="loading" ></div>
        <?php echo $this->content; ?> 
        <div id="home-logo" class="mathi2"  style="display:none;position:fixed;left:0;top:0;"><img src="<?php echo $this->basePath(). 'img/newnobsmall.svg'?>" style="width:75px; height:75px;"/></div>
    </body>
</html>
