<div class="modal fade" data-modal="sign" id="sign-modal" >
    <div class="modal-dialog">
            <form  role="form"  method="POST"  id="form" >	
                    <div class="modal-content">
                        <div class="modal-header">
<!--                            <div id="modal-img"><img style="height:70px;width:70px;" src="<?php echo $this->basePath() . '/img/newnobsmall.png';?>"/></div>-->
                           <h3 id="modal-title">Sign In</h3>
                        </div>
                        <div id="fb-login-button-container" class="modal-body">
                           
                        </div>
                        <div class="modal-footer">  
                            <button class="modalShut btn btn-danger">Cancel</button>
                        </div>
                    </div>
            </form>
    </div>
</div>
