<section id="fullpage" class="changeMe">
    <section  class="section " id='first-Page'>
        <div id="our-slider-container" class="container  NepalOnBoardContainer">
            <div class="item active nepalOnboardBack" id="first-slide">    
            </div>
        </div>
        <div class="container NepalOnBoardContainer mathi3level" id="top-most-block">
            <div id="socialMediaContainer" class="col-md-3 " >

            </div>
            <div id="logoContainer" class="col-md-5  ">
                <img title="Nepal onboard logo" id="nepOnboardImage" src="<?php echo $this->basePath('img/newnob.svg') ?>" alt="Nepal On-Board"/>
            </div>
        </div>
        <section class="container mathi3level" id="mission-statement-section">
            <div class="col-md-12" id="mission-statement-container">
                <h1 title="Nepal onboard tag line" id="mission-statement">convenience at your fingertips</h1>
            </div>
            <div class="col-md-12" id="below-mission-statement"><h1 id="saveY" >Save your time, go <span class="importantWord">online</span></h1></div>
        </section>

        <div class="container mathi3level" id="arrow-wrapper">
            <div class="col-md-4 col-md-push-4 col-xs-4 col-xs-push-5 arrowContainer " >
                <a class="NepalOnBoardLink" href='#menuPage' id="down-arrow"><i class="fa fa-3x fa-arrow-circle-o-down" id="hacha"></i></a>
            </div>
        </div>
    </section>
    <section class="section" id='second-Page'>
        <div class="col-md-12 mathi3level NepalOnBoardContainer" id="second-page-main">
            <div class="upper col-md-12">
                <h1 class="slanted"> Coming Soon..</h1>
            </div>
            <div class="belowComingSoon col-md-12">
                <div class="functionalityIcon col-md-3 col-md-push-5"> 
                </div>
                <div class="col-md-12">
                    <div id="form-container" class="col-md-6 col-md-push-3 col-lg-6 col-lg-push-3">
                        <form data-url="<?php echo $this->currentUrl;?>" id="messageForm" role="form" method="post">
                            <div class="form-group">
                                <input  value='' name="email" class="input-lg" placeholder="be the first one to board when we go live" type="text" id="emailid" style="border-radius:0px;;border:1px solid white !important;width:27em;padding-left:2em;"/>
                                <i id="icon" class="fa fa-2x fa-envelope" ></i>
                                <button type="submit" class="btn btn-default btn" id="hail-button">Notify me</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="messageContainer col-md-12">
                    <h4 id="messageOnSubmission" class='message'>
                        
                    </h4>
                </div>
                <div id="ourMessageContainer" class="messageContainer col-md-12">
                    <h3 id="ourMessage" class="message">
                        Stay tuned to experience our elegant and convenient new features.<br/>
                        In the meantime feel free to read our blogs and learn about us.
                    </h3>
                </div>
                <div class="NepalOnBoardContainer menuList">
                    <div id="us" class="col-md-4 col-sm-4 col-xs-4"> 
                        <hr class="lowerhr"/>
                        <div class="menu lower us">
                            <img alt="About Us" class="menu-icons" src="<?php echo $this->basePath() . 'img/About.svg'?>"/>
                        </div>
                        <div class="optionName lowerOption us "><h3 >about us</h3></div>
                    </div>
                    <div id="contact" class="col-md-4 col-sm-4 col-xs-4"> 
                        <hr class="lowerhr"/>
                        <div class="menu lower contact ">
                        <img class="menu-icons" alt="Contact Us" src="<?php echo $this->basePath() . 'img/Contact.svg'?>"/>
                        </div>
                        <div class="optionName lowerOption contact"><h3>contact us</h3></div>
                    </div>
                    <div id="article" class="col-md-4 col-sm-4 col-xs-4"> 
                        <hr class="lowerhr"/>
                        <div data-direction="<?php echo $this->basePath() . '/blog' ?>" class="menu lower article">
                            <img class="menu-icons" alt="Article" src="<?php echo $this->basePath() . 'img/Article.svg'?>"/>
                        </div>
                        <div data-direction="<?php echo $this->basePath() . '/blog' ?>" class="optionName lowerOption article"><h3 id="articleHeading">blog</h3></div>
                    </div>
                </div>
        </div>
    </section>
    <section class="section " id="third-Page">
        <div id="our-slider-container" class="container NepalOnBoardContainer thirdPageBg nepalOnboardBack">
        </div>
         <div class="dhakeko">
         </div>
        <div class="col-md-12 NepalOnBoardContainer" id="aboutUs"> 
            <div class="col-md-12" id="aboutContent">
                <div class="mathi col-md-4 col-md-push-4">
                    <div style="border:2px solid #003366;margin:15px;">
                    <h1 id="about-us-heading">about us</h1>
                    </div>
                    </div>
                <div class="col-md-4">
                    
                </div>
            </div>
            <div id="we" class="mathi col-md-push-2 col-md-8">
                Two graduates from Sydney who dream of making it easier for other international students are here to help with Nepal onboard. Our aim is to give you a convenient platform to use, taking the pressure off you in planning your journey to a new Country. 
                We want to promote the use of technology as safe and it is our passion to provide you with a unique application that is easy, transparent, reliable and simple. 
            </div>
            <div id="about-features-container" class="mathi col-md-12">
                <div class=" aboutFeatures col-md-5" id="about-house">
                      <div class="featuresHeading">
                          <div class="insideAboutPic" id="house-pic"><img class="aboutIcons" src="<?php echo $this->basePath() . 'img/house.svg'?>" /></div>
                       </div>
                     Don’t have a place to live? We’ve got it covered. Our feature ‘Board A House’ lists down the available rooms and share houses around the area that you choose. Find accommodation with only a few easy steps. Nepal Onboard is convenience right at your fingertips. 
                </div>
                <div class="col-md-2"></div>
                <div class=" aboutFeatures col-md-5" id="about-plane">
                     <div class="featuresHeading">
                        <div class="insideAboutPic"><img class='aboutIcons' src="<?php echo $this->basePath() . 'img/plane.svg'?>" /></div>
                    </div>
                     Nepal onboard’s ‘Board a Plane’ feature will enable you to book domestic and international flights from where you are seated. We try our level best to cater to you with real time student discounts, fast responses and correct information in the palm of your hand. 
                </div>
            </div>
        </div>
      
    </section>
    <section class="section f" id="fourth-page">
        <div class="NepalOnBoardContainer" id="contact-background-pic-container">
                <img id="contact-pic" src="<?php echo $this->basePath() . 'img/namaste.jpg'?>" />
                <div class="dhakeko" style="height:100%;background-color:rgb(72, 57, 0);">
                </div>
         </div>
        <div class=" NepalOnBoardContainer " >
            <div id="contact-top" class="col-md-12 mathi2" >
                <div id="contact-container">
                    <h1 id="contact-heading">contact us</h1>
                </div>
            </div>         
            <div  class="col-md-12" id="contactblockcontainer" > 
                <div id="formblock" class="col-md-5 mathi  contactblock">
                    <form role="form"  data-url="<?php echo $this->basePath('/application/initial/message');?>" method="post" id="feedbackform">   
                        <div class="col-md-12 form-group">
                            <fieldset><legend> Name </legend></fieldset>
                            <span>
                                <input class="form-control nobinput" name="feedback[name]" id="nameField" type="text" >
                            </span>
                            <i class="fa feedbackicons fa-user" ></i>
                        </div>
                        <div class="col-md-12 form-group">
                            <fieldset><legend> Email </legend></fieldset>
                            <span>
                                <input class="form-control nobinput" name="feedback[email]" id="" type="email"/>
                            </span>
                            <i class="fa feedbackicons fa-envelope-square" ></i>
                        </div>
                        <div class="col-md-12 form-group">
                           <fieldset><legend> Message </legend></fieldset>
                            <i   class="fa feedbackicons fa fa-pencil" ></i>
                            <textarea name="feedback[message]" class="form-control nobinput" id="feedback-textarea"></textarea>
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" id="feedbackbutton" class="btn  btn-default col-md-3">Send</button>
                            <img id="success" class="result"  src="<?php echo $this->basePath() .'/img/success.svg'?>"> 
                            <img id="fail" class="result"  src="<?php echo $this->basePath() .'/img/error.svg'?>"> 
                        </div>                      
                    </form>
                    <div id="error-message-container">
                        <p>         
                        </p>
                    </div>
                </div>
                <div class="col-md-2 mathi"></div>
                <div class="col-md-5 mathi contactblock" id="social-media-info-container"> 
                    <div class="col-md-12 contactDetailsContainer">
                        <span id="contactDetailsContaier">
                            <img class="contactIcons" src="<?php echo $this->basePath() .'img/technology.svg'?>"/>
                        </span>
                        <span class="contactdetails" style="position: relative;top:-0.5em;">
                           +61 451595506 
                        </span>
                        <span class="contactdetails" style="position: relative;top: 1em;left: -7em;">
                          +61 452460026 
                        </span>
                    </div>
                    <div class="col-md-12 contactDetailsContainer">
                        <span id="email-icon-container">
                             <img class="contactIcons" src="<?php echo $this->basePath() .'img/closed-envelope-circle.svg'?>"/>
                        </span>
                        <span class="contactdetails">
                            service@nepalonboard.com
                        </span>
                    </div>
                    <div class="col-md-12 col-xs-12 socialMediaContainer" >
                        <h1 id="follow-us" >Follow us on</h1> 
                    </div>
                    <div class="col-md-12 socialMediaContainer col-xs-12">
                        <a class="social" id="social-media-facebook" target="blank" href="https://www.facebook.com/1058562654187261"><span class=" fa fa-5x fa-facebook-square"></span></a>
                        <a class="social" id="social-media-instagram" href="#"><span class="nobsocial fa fa-5x fa-instagram"></span></a>
                        <a class="social" id="social-media-googleplus" target="blank" href="https://plus.google.com/u/0/100834822587027939707"><span class="nobsocial fa fa-5x fa-google-plus"></span></a>
                   </div>
       
                </div>
            </div>
             <div class="col-md-12 col-xs-12" id="copyright">
                        <h4>&copy; Copyright Nepal Onboard <?php echo $this->currentDate;?></h4>
             </div>
        </div>
    </section>
</section>


